server:
  http_addr: ":5555"
  grpc_addr: ":5556"
  debug_addr: ":5557"

clients:
  seq_db:
    - id: "default-seq-db"
      addrs:
        - "seq-db-proxy:9004"
      timeout: 15s
    - id: "test-seq-db"
      addrs:
        - "seq-db-proxy:9005"
      timeout: 15s

handlers:
  seq_api:
    default_env: "production"
    max_search_limit: 100
    max_export_limit: 100
    max_parallel_export_requests: 10
    pinned_fields:
      - name: level
        type: keyword
      - name: message
        type: text

    envs:
      production:
        seq_db_id: "default-seq-db"
        options:
          max_search_limit: 1000
          max_export_limit: 500

      staging:
        seq_db_id: "test-seq-db"
        options:
          max_search_limit: 200
          max_export_limit: 200
